// Learn more about Vitest configuration options at https://vitest.dev/config/

import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html', 'lcov'],
      // Generated by `npm run api:generate` (orval) - not hand-written, so excluded from coverage.
      exclude: ['src/app/api/generated/**']
    }
  }
});
